# Generated by Django 6.0.6 on 2026-06-15 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Website",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=120)),
                ("url", models.URLField(unique=True)),
                ("performance_threshold", models.PositiveSmallIntegerField(default=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PageSpeedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strategy", models.CharField(max_length=10)),
                (
                    "performance_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "accessibility_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "best_practices_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("seo_score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("first_contentful_paint", models.FloatField(blank=True, null=True)),
                ("largest_contentful_paint", models.FloatField(blank=True, null=True)),
                ("total_blocking_time", models.FloatField(blank=True, null=True)),
                ("cumulative_layout_shift", models.FloatField(blank=True, null=True)),
                ("speed_index", models.FloatField(blank=True, null=True)),
                ("interaction_to_next_paint", models.FloatField(blank=True, null=True)),
                ("status", models.CharField(default="success", max_length=20)),
                ("error_message", models.TextField(blank=True)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="tracker.website",
                    ),
                ),
            ],
        ),
    ]
