# Generated by Django 6.0.6 on 2026-06-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagespeedreport",
            name="time_to_first_byte",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
