# Generated by Django 6.0.6 on 2026-06-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_pagespeedreport_time_to_first_byte"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagespeedreport",
            name="field_cls",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pagespeedreport",
            name="field_fcp",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pagespeedreport",
            name="field_inp",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pagespeedreport",
            name="field_lcp",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pagespeedreport",
            name="field_ttfb",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
