# Generated by Django 6.0.6 on 2026-06-16 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tracker",
            "0003_pagespeedreport_field_cls_pagespeedreport_field_fcp_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alert_type", models.CharField(max_length=50)),
                (
                    "score_at_alert",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("sent_to", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("delivered", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tracker.pagespeedreport",
                    ),
                ),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="tracker.website",
                    ),
                ),
            ],
        ),
    ]
