# Generated by Django 6.0.6 on 2026-06-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_alertlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="website",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
