# Generated by Django 6.0.6 on 2026-06-18 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0005_website_is_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="website",
            name="alert_cooldown_minutes",
            field=models.PositiveIntegerField(default=1440),
        ),
        migrations.AddField(
            model_name="website",
            name="alert_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="website",
            name="notification_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="website",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
